// scripts/sourceStoryBatch/build.ts

import fs from "fs"
import path from "path"
import type { RawSourceStory } from "./loadSourceStoriesFromTSV"

export function buildSourceStories(stories: RawSourceStory[]) {
  const outputPath = path.resolve(
    process.cwd(),
    "src/data/sourceStories/generated.ts"
  )

  const content = `// ⚠️ AUTO-GENERATED FILE. DO NOT EDIT.
// Generated by scripts/sourceStoryBatch

import type { SourceStory } from "./types"

export const sourceStories: SourceStory[] = ${JSON.stringify(
    stories,
    null,
    2
  )}
`

  fs.mkdirSync(path.dirname(outputPath), { recursive: true })
  fs.writeFileSync(outputPath, content, "utf-8")

  console.log(`✔ generated.ts written (${stories.length} stories)`)
}
