// ⚠️ AUTO-GENERATED FILE. DO NOT EDIT.
// Generated by scripts/sourceStoryBatch

import type { SourceStory } from "./types"

export const sourceStories: SourceStory[] = [
  {
    "id": "rampo_labyrinth",
    "structural_functions": [
      "ordered_world",
      "taboo",
      "temptation",
      "transgression",
      "observer_distortion",
      "erosion",
      "void_ending"
    ],
    "tone": "dark|uncanny|psychological|decadent",
    "text": "〈キャラ〉は、いつからか終わりの見えぬ回廊を歩いていた。白と黒だけで構成された幾何学的な廊下は左右対称でありながら、どこか微妙に狂っている。〈キャラ〉はそれを美しいと感じてしまった自分に嫌悪を覚えた。\\n\\n壁には押絵が掛けられていた。人とも獣ともつかぬ肢体、裂け目のような笑み。それらはどれも〈キャラ〉自身の身体を歪めて誇張したもののように見えた。\\n\\n〈キャラ〉は知っている。この迷宮では、見てはならぬものほど最も精巧に作られている。\\n\\n押絵に触れた瞬間、回廊は増殖した。一本道は無数の分岐となり、〈キャラ〉は歩いているのか観察されているのか分からなくなる。\\n\\nやがて理解する。この迷宮が写しているのは外界ではない。美を求め、同時にそれを壊したいと願う、〈キャラ〉自身の内部構造なのだ。"
  },
  {
    "id": "kenji_orders",
    "structural_functions": [
      "ordered_world",
      "temptation",
      "transgression",
      "division",
      "inversion",
      "void_ending"
    ],
    "tone": "dark|surreal|folkloric|gentle-horror",
    "text": "〈キャラ〉は、親切すぎる標識に導かれて迷宮へ入った。「こちらへどうぞ」「安心してお進みください」その言葉はどこまでも丁寧だった。\\n\\n扉を一枚通るごとに、〈キャラ〉は何かを要求される。靴を脱ぎ、名前を置き、記憶を一つ差し出す。\\n\\n回廊は明るく清潔で礼儀正しい。だが〈キャラ〉は、その丁寧さの奥に潜む残酷さを感じ取っていた。\\n\\n最後の扉にはこう書かれていた。「あなた自身であることを、どうぞお忘れください」\\n\\n〈キャラ〉は一瞬迷い、それでも扉を開く。そこに待っていたのは、何者でもない〈キャラ〉自身であった。"
  },
  {
    "id": "ende_freedom_prison",
    "structural_functions": [
      "ordered_world",
      "taboo",
      "transgression",
      "stagnation",
      "division",
      "erosion",
      "consequence",
      "inversion",
      "exile",
      "void_ending"
    ],
    "tone": "philosophical|allegorical|quiet_dark",
    "text": "〈キャラ〉は自由を求めて迷宮に入った。ここには鍵も番人もなく、ただ無限の選択肢があるだけだった。\\n\\n右へ行く自由、左へ戻る自由、立ち止まる自由。〈キャラ〉はそれを祝福だと思った。\\n\\nだが選択肢が増えるほど、〈キャラ〉は動けなくなる。迷宮は語りかける。「どれも正しい」「どれも間違っていない」\\n\\n〈キャラ〉は悟る。ここでは決断こそが最大の罪なのだと。\\n\\n自由は〈キャラ〉を縛り、迷宮は〈キャラ〉の内側に完成する。"
  },
  {
    "id": "borges_structure",
    "structural_functions": [
      "ordered_world",
      "taboo",
      "transgression",
      "stagnation",
      "division",
      "erosion",
      "consequence",
      "inversion",
      "exile",
      "void_ending"
    ],
    "tone": "intellectual|metaphysical|abstract",
    "text": "〈キャラ〉は迷宮の中心で一冊の書物を見つける。その題名は〈キャラ〉自身の名前だった。\\n\\n書物には、〈キャラ〉が選んできたすべての選択が記されている。だが読み進めると、まだ選んでいない未来までもが既に書かれていた。\\n\\n〈キャラ〉は悟る。この迷宮は空間ではない。構造そのものが〈キャラ〉なのだ。\\n\\n書物を閉じた瞬間、迷宮は消える。残るのは、読む者を失った一冊の本だけである。"
  },
  {
    "id": "ango_sakura",
    "structural_functions": [
      "ordered_world",
      "taboo",
      "temptation",
      "taboo",
      "inversion",
      "transgression",
      "erosion",
      "observer_distortion",
      "consequence"
    ],
    "tone": "grotesque|tragic|dark_romantic",
    "text": "満開の桜の下で、〈キャラ〉は人であることを疑い始めた。美しさはあまりにも無防備で、あまりにも残酷だった。\\n\\n夜桜は正しさも倫理も一様に照らし出す。〈キャラ〉はその光の中で、自分の醜さを否定しなかった。\\n\\n桜は何も裁かない。だからこそ、〈キャラ〉は逃げ場を失う。"
  },
  {
    "id": "poe_heartbeat",
    "structural_functions": [
      "division",
      "transgression",
      "erosion",
      "temptation",
      "stagnation",
      "observer_distortion",
      "void_ending"
    ],
    "tone": "claustrophobic|obsessive|gothic",
    "text": "〈キャラ〉は壁の奥で音を聞いた。それは迷宮の鼓動であり、同時に〈キャラ〉自身の心音でもあった。\\n\\n逃げるほど音は近づき、立ち止まるほど世界は歪む。\\n\\n〈キャラ〉は理解する。この迷宮に出口はない。出口とは沈黙だからだ。"
  },
  {
    "id": "japanese_kaiki",
    "structural_functions": [
      "taboo",
      "division",
      "erosion",
      "transgression",
      "temptation",
      "exile",
      "inversion",
      "consequence",
      "void_ending"
    ],
    "tone": "dark|eerie|mythic|ominous",
    "text": "回廊は〈キャラ〉の名を一文字ずつ奪っていく。名を失うたび、身体は軽く、心は曖昧になる。\\n\\n最後に残ったのは美しさだけだった。それが誰のものか、〈キャラ〉にはもう分からない。"
  }
]
